_1.Batch211.Web/Controllers/DokumenController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _3.Batch211.DataAccess;
using _2.Batch211.ViewModel;

namespace _1.Batch211.Web.Controllers
{
    public class DokumenController : Controller
    {
        // GET: Dokumen
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {

            return PartialView("List", DokumenDataAccess.GetListAll());
        }

        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        public JsonResult UploadFiles(DokumenViewModel model)
        {
            model.created_by = 1;
            model.created_on = DateTime.Now;
            model.is_delete = false;
            model.biodata_id = 1;

            // Checking no of files injected in Request object  
            if (Request.Files.Count > 0)
            {
                try
                {
                    HttpFileCollectionBase files = Request.Files;

                    HttpPostedFileBase file = files[0];
                    string fileName = file.FileName;

                    // create the uploads folder if it doesn't exist
                    Directory.CreateDirectory(Server.MapPath("~/UploadedFiles/"));
                    string path = Path.Combine(Server.MapPath("~/UploadedFiles/"), fileName);

                    // save the file
                    file.SaveAs(path);
                    return Json("File uploaded successfully");

                }

                catch (Exception e)
                {
                    return Json("error" + e.Message);
                }
            }
            return Json("no files were selected !");
            
        }
    }
}

_1.Batch211.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _1.Batch211.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

_1.Batch211.Web/Controllers/KeahlianController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _3.Batch211.DataAccess;
using _2.Batch211.ViewModel;

namespace _1.Batch211.Web.Controllers
{
    public class KeahlianController : Controller
    {
        // GET: Keahlian
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {
            
            return PartialView("List", KeahlianDataAccess.GetListAll());
        }
        public ActionResult Create()
        {
            ViewBag.KeahlianList = KeahlianDataAccess.KeahlianCollection();
            //ViewBag.CategoriesList = Models.Helper.ToSelectList(KeahlianDataAccess.CategoriesCollection(), "Id", "Name");
            return PartialView("_Create");
        }
        [HttpPost]
        public ActionResult Create(KeahlianViewModel model)
        {
            model.created_by = 1;
            model.created_on = DateTime.Now;
            model.is_delete = false;
            model.biodata_id = 1;
        
            if (KeahlianDataAccess.Insert(model))
            {
                return Json(new
                {
                    success = true,
                    message = "Berhasil"
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new
                {
                    success = false,
                    message = KeahlianDataAccess.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Edit(long id)
        {
            ViewBag.KeahlianList = KeahlianDataAccess.KeahlianCollection();
            return PartialView("_Edit", KeahlianDataAccess.GetDetailsById(id));
        }

        [HttpPost]
        public ActionResult SaveEdit(KeahlianViewModel model)
        {
            if (KeahlianDataAccess.Update(model))
            {
                return Json(new { success = true, message = "berhasil" },
                    JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, message = KeahlianDataAccess.Message },
                    JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Delete(long id)
        {
            ViewBag.KeahlianList = KeahlianDataAccess.KeahlianCollection();
            return PartialView("_Delete", KeahlianDataAccess.GetDetailsById(id));
        }

        [HttpPost]
        public ActionResult SaveDelete(KeahlianViewModel model)
        {
            model.created_by = 1;
            model.created_on = DateTime.Now;
            model.is_delete = false;
            model.biodata_id = 1;

            if (KeahlianDataAccess.Delete(model))
            {
                return Json(new
                {
                    success = true,
                    message = "Berhasil"
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new
                {
                    success = false,
                    message = KeahlianDataAccess.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

_1.Batch211.Web/Controllers/PelamarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using _2.Batch211.ViewModel;
using _3.Batch211.DataAccess;

namespace _1.Batch211.Web.Controllers
{
    public class PelamarController : Controller
    {
        // GET: Pelamar
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Search(string kataKunci, int? page)
        {
            
            return PartialView("_List", PelamarDataAccess.Search(kataKunci));

        }
        public ActionResult OrderByAsc(string kataKunci)
        {
            return PartialView("_List", PelamarDataAccess.OrderByAsc(kataKunci));
        }
        public ActionResult OrderByDesc(string kataKunci)
        {
            return PartialView("_List", PelamarDataAccess.OrderByDesc(kataKunci));
        }

    }
}

_1.Batch211.Web/Controllers/PenjadwalanRencanaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _2.Batch211.ViewModel;
using _3.Batch211.DataAccess;

namespace _1.Batch211.Web.Controllers
{
    public class PenjadwalanRencanaController : Controller
    {
        // GET: PenjadwalanRencana
        public ActionResult Index()
        {
            return View();
        }
        //public ActionResult List()
        //{
        //    return PartialView("List", Pe.GetListAll());
        //}
    }
}

_1.Batch211.Web/Views/Dokumen/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel-group">
    <div class="panel panel-default">

        <div class="panel-heading">
            <button typeof="button" id="btn-add" class="btn btn-default" title="Create New">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Tambah Keahlian
            </button>
        </div>

        <div class="panel-body">
            <div id="table-list">

            </div>
        </div>

    </div>
</div>

<div id="modal-form" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="panel-group">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 id="modal-title">Keahlian</h3>
                </div>

                <div id="modal-body" class="modal-body panel-body">
                    <p>Modal body text goes here.</p>
                </div>

                <div id="modal-footer" class="modal-footer" style="display:none">

                </div>

            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        var progHtml = '<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar" style="width:100%"/></div>'

        $(document).ready(function ()
        {
            ShowList();
        });

        function ShowList()
        {
            $("#table-list").html(progHtml);

            $.ajax({
                url: '@Url.Action("List", "Dokumen")', /*nama method di controller, nama controller*/
                type: 'get', /*proses mengambil data dengan 'get' */
                success: function (result) {
                    //debugger;
                    $("#table-list").html(result);
                }
            });
        }


        $("#btn-add").click(function () {
            $("#modal-title").html("Dokumen");
            $("#modal-body").html(progHtml);
            $("#modal-form").modal("show");

            $.ajax({
                url: '@Url.Action("Create", "Dokumen")',
                type: 'get',
                success: function (result) {
                    $("#modal-body").html(result);
                }
            })
        });


    </script>
}

_1.Batch211.Web/Views/Dokumen/_Create.cshtml
@model _2.Batch211.ViewModel.DokumenViewModel

@using (Html.BeginForm("Create", "Dokumen", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.file_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.file_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.file_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.file_path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    <input id="fileupload" type="file" name="fileupload" @*accept="text/x-csv"*@ required/>
                @*<td width="100px">
                    <input type="button" id="btn_upload" value="Upload" onclick="uploadFile()" />
                </td>*@
                @*<input type="file" name="ImageFile" id="ImageFile" required />*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="button" id="btn_upload" value="Upload" class="btn btn-success" onclick="uploadFile()">Create New</button>
                <button type="button" value="Cancel" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
}

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@
<script>
    $("#btn_upload").click(function () {
    if (window.FormData == undefined)
        alert("Error: FormData is undefined");

    else {
        
        var fileUpload = $("#fileupload").get(0);
        var files = fileUpload.files;

        var fileData = new FormData();

        fileData.append(files[0].name, files[0]);

        var item = {
            id: 0,
            file_name: $("#file_name").val(),
            file_path: $("#file_path").val(),
            notes: $("#notes").val()
        }

        $.ajax({
            url: '/Dokumen/UploadFiles',
            type: 'post',
            datatype: 'json',
            contentType: false,
            processData: false,
            async: false,
            data: fileData, item,
            success: function (response) {
                alert(response);
                $("#modal-form").modal("hide");
                ShowList();
            }
        });
    }

});
    //function uploadFile() {
    //    // Checking whether FormData is available in browser
    //    if (window.FormData !== undefined) {
    //        var fileUpload = $("#fileupload").get(0);
    //        var files = fileUpload.files;
    //        // Create FormData object
    //        var fileData = new FormData();
    //        // Looping over all files and add it to FormData object
    //        for (var i = 0; i < files.length; i++) {
    //            fileData.append(files[i].name, files[i]);
    //        }
    //        // Adding one more key to FormData object
    //        //fileData.append('username', ‘Manas’);
    //        $.ajax({
    //            url: 'Dokumen/UploadFiles',
    //            type: "POST",
    //            contentType: false, // Not to set any content header
    //            processData: false, // Not to process data
    //            data: fileData,
    //            success: function (result) {
    //                if (result.split("-")[1] == "true") {
    //                    toastr.success(result.split("-")[0]);
    //                    OnSearch(1);
    //                } else {
    //                    toastr.error(result.split("-")[0], 'Error', { timeOut: 5000 });
    //                }
    //            },
    //            error: function (err) {
    //                toastr.error(err.statusText, 'Error', { timeOut: 5000 });
    //            }
    //        });
    //    } else {
    //        toastr.error("FormData is not supported.", 'Error', { timeOut: 5000 });
    //    }
    //}

    @*$("#btn_save").click(function () {
        var formData = new FormData();
        var totalFiles = document.getElementById("ImageFile").files.length;


        for (var i = 0; i < totalFiles; i++)
            {
                var file = document.getElementById("ImageFile").files[i];
                formData.append("ImageFile", file);
            }

        var item = {
            id: 0,
            file_name: $("#file_name").val(),
            file_path: $("#file_path").val(),
            ImageFile: formData,
            notes: $("#notes").val()
        }
        $.ajax({
            url: '@Url.Action("SaveCreate", "Dokumen")',
            type: 'post',
            data: { file: formData },
            success: function (result) {
                $("#modal-form").modal("hide");
                ShowList();
            }
        });
    })*@
</script>

_1.Batch211.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

_1.Batch211.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

_1.Batch211.Web/Views/Keahlian/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>Index</h2>*@
<br />
<div class="panel-group">
    <div class="panel panel-default">

        <div class="panel-heading">
            <button typeof="button" id="btn-add" class="btn btn-default" title="Create New">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Tambah Keahlian
            </button>
        </div>

        <div class="panel-body">
            <div id="table-list">

            </div>
        </div>

    </div>
</div>

<div id="modal-form" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="panel-group">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 id="modal-title">Keahlian</h3>
                </div>

                <div id="modal-body" class="modal-body panel-body">
                    <p>Modal body text goes here.</p>
                </div>

                <div id="modal-footer" class="modal-footer" style="display:none">

                </div>

            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        var progHtml = '<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar" style="width:100%"/></div>'

        $(document).ready(function ()
        {
            ShowList();
        });

        function ShowList()
        {
            $("#table-list").html(progHtml);

            $.ajax({
                url: '@Url.Action("List", "Keahlian")', /*nama method di controller, nama controller*/
                type: 'get', /*proses mengambil data dengan 'get' */
                success: function (result) {
                    //debugger;
                    $("#table-list").html(result);
                }
            });
        }


        $("#btn-add").click(function () {
            $("#modal-title").html("Keahlian");
            $("#modal-body").html(progHtml);
            $("#modal-form").modal("show");

            $.ajax({
                url: '@Url.Action("Create", "Keahlian")',
                type: 'get',
                success: function (result) {
                    $("#modal-body").html(result);
                }
            })
        });


    </script>
}

_1.Batch211.Web/Views/Keahlian/_Create.cshtml
@model _2.Batch211.ViewModel.KeahlianViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.skill_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.skill_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.skill_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.skill_level_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("skill_level_id", new SelectList(ViewBag.KeahlianList, "id", "name", "--Pilih--"), new { @class = "form-control" })
                @*@Html.DropDownListFor(model => model.skill_level_id, ViewBag.KeahlianList as SelectList, new { @class = "form-control" } )*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="button" id="btn_save" value="Create" class="btn btn-success">Create New</button>
                <button type="button" value="Cancel" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>

        }

<script>
    $("#btn_save").click(function () {
        var item = {
            id: 0,
            skill_name: $("#skill_name").val(),
            skill_level_id: $("#skill_level_id").val(),
            notes: $("#notes").val()
        }
        $.ajax({
            url: '@Url.Action("Create", "Keahlian")',
            type: 'post',
            data: { model: item },
            success: function (result) {
                $("#modal-form").modal("hide");
                ShowList();
            }
        });
    })
</script>

_1.Batch211.Web/Views/Keahlian/_Delete.cshtml
@model _2.Batch211.ViewModel.KeahlianViewModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KeahlianViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.skill_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.skill_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.skill_level_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.skill_level_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.notes)
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(Model => Model.id)

        <div class="form-actions no-color">
            <input type="button" value="Delete" title="Delete" class="btn btn-danger" id="btn_save_delete" />
            <input type="button" value="Cancel" title="Cancel" class="btn btn-default" data-dismiss="modal" />
        </div>
    }
</div>

<script>
    $("#btn_save_delete").click(function () {
        var item = {
            id: $("#id").val()
        };

        $.ajax({
            url: '@Url.Action("SaveDelete", "Keahlian")',
            type: 'post',
            data: { model: item },
            success: function (result) {
                if (result.success) {
                    $("#modal-form").modal("hide");
                    ShowList();
                }
                else {
                    $("#modal-footer").show();
                    $("#modal-footer").html(result.message);
                }
            }
        });
    });
</script>

_1.Batch211.Web/Views/Keahlian/_Edit.cshtml
@model _2.Batch211.ViewModel.KeahlianViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        
        <div class="form-group">
            @Html.LabelFor(model => model.skill_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.skill_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.skill_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.skill_level_id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("skill_level_id", new SelectList(ViewBag.KeahlianList, "id", "name", "--Pilih--"), new { @class = "form-control" })
                @*@Html.EditorFor(model => model.skill_level_id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.skill_level_id, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="button" id="btn_save" value="Create" class="btn btn-success">Save</button>
                <button type="button" value="Cancel" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
}

<script>
    $("#btn_save").click(function () {
        var item = {
            id: $("#id").val(),
            skill_name: $("#skill_name").val(),
            skill_level_id: $("#skill_level_id").val(),
            notes: $("#notes").val()
        };
        alert("message");
        $.ajax({
            url: '@Url.Action("SaveEdit", "Keahlian")',
            type: 'post',
            data: { model: item },
            success: function (result) {
                if (result.success) {
                    $("#modal-form").modal("hide");
                    ShowList();
                }
                else {
                    $("#modal-footer").show();
                    $("#modal-footer").html(result.message);
                }
            }
        });
    })
</script>

_1.Batch211.Web/Views/Pelamar/_PopUpPelamar.cshtml
<div class="modal fade skin-blue-light" id="modal-form-detail-pelamar" role="dialog">
    <div class="modal-dialog  modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title" id="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body" id="modal-body">

                <div class="container-fluid">
                    <div class="row row-no-gutters">
                        <div class="col-sm-3">
                            <div class="list-group">
                                <a class="list-group-item list-group-item-action">Profil</a>
                                <a class="list-group-item list-group-item-action">Biodata</a>
                                <a class="list-group-item list-group-item-action">Pengalaman Kerja</a>
                                <a class="list-group-item list-group-item-action">Pendidikan</a>
                                <a class="list-group-item list-group-item-action">Pelatihan</a>
                                <a class="list-group-item list-group-item-action">Sertifikasi</a>
                                <a class="list-group-item list-group-item-action">Sumber Lowongan Kerja</a>
                                <a class="list-group-item list-group-item-action">Organisasi</a>
                                <a class="list-group-item list-group-item-action">Keluarga</a>
                                <a class="list-group-item list-group-item-action">Keahlian</a>
                                <a class="list-group-item list-group-item-action">Lain - lain</a>
                                <a class="list-group-item list-group-item-action">Dokumen</a>
                                <a class="list-group-item list-group-item-action">Catatan</a>
                                <a class="list-group-item list-group-item-action">Aktivasi Akun</a>
                                <a class="list-group-item list-group-item-action">Lihat Tes</a>
                                <a class="list-group-item list-group-item-action">Hasil Tes</a>
                            </div>
                        </div>
                        <div class="col-sm-9">Content</div>
                    </div>
                </div>

            </div>
            <div class="modal-footer" id="modal-footer">
            </div>
        </div>

    </div>
</div>


<script>
    function ProfilClick() {
        $("#modal-title").html("Detail Pelamar");
        $("#modal-form").modal("show");

         $.ajax({
                url: '@Url.Action("ProfilPelamar", "Pelamar")',
                type: 'get',
                success: function (result) {
                    $("#modal-body").html(result);
                }
            });
    }
</script>

_1.Batch211.Web/Views/PenjadwalanRencana/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<br />
<div class="panel-group">
    <div class="panel panel-default">

        <div class="panel-heading">
            <button typeof="button" id="btn-add" class="btn btn-default" title="Create New">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Create New
            </button>
        </div>

        <div class="panel-body">
            <div id="table-list">

            </div>
        </div>

    </div>
</div>

<div id="modal-form" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="panel-group">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 id="modal-title">Category</h3>
                </div>

                <div id="modal-body" class="modal-body panel-body">
                    <p>Modal body text goes here.</p>
                </div>

                <div id="modal-footer" class="modal-footer" style="display:none">

                </div>

            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        var progHtml = '<div class="progress progress-striped active" style="margin-bottom:0"><div class="progress-bar" style="width:100%"/></div>'

        $(document).ready(function ()
        {

            ShowList();
        });

        function ShowList()
        {
            $("#table-list").html(progHtml);

            $.ajax({
                url: '@Url.Action("List", "Dokumen")', /*nama method di controller, nama controller*/
                type: 'get', /*proses mengambil data dengan 'get' */
                success: function (result) {
                    $("#table-list").html(result);
                }
            });
        }


        $("#btn-add").click(function () {
            $("#modal-title").html("Dokumen");
            $("#modal-body").html(progHtml);
            $("#modal-form").modal("show");

            $.ajax({
                url: '@Url.Action("Create", "Dokumen")',
                type: 'get',
                success: function (result) {
                    $("#modal-body").html(result);
                }
            })
        });
    </script>
}